# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  skk-dict = {
    pname = "skk-dict";
    version = "fd3cfbd84a846b773f4587be636e1a29f800ef8a";
    src = fetchFromGitHub {
      owner = "banjun";
      repo = "skk-jisyo-imasparql";
      rev = "fd3cfbd84a846b773f4587be636e1a29f800ef8a";
      fetchSubmodules = false;
      sha256 = "sha256-0a7Po9LKzrKYfg0kcrq5QfxJiIw/RDr/3E96We7J5NU=";
    };
    date = "2024-08-28";
  };
}
